#%RAML 1.0
title: test api
/todos:
  displayName: Todos
  get:
    displayName: Get all todos
  post:
    displayName: Create a new todo
  put:
    displayName: Create or update a todo
  patch:
    displayName: Partially update a todo
  delete:
    displayName: Delete a todo
  head:
    displayName: check endpoint
  options:
    displayName: get allowed methods